throw process.on("uncaughtException",function(e){throw console.log("blah"),e}),"on purpose";